/**
 * Everything the pages tell a crawler about themselves.
 *
 * Absolute URLs are built here rather than left to Next's metadataBase
 * resolution. The site is served from a repository sub-path, and a bare "/…"
 * handed to Metadata resolves against the origin in some code paths and against
 * the sub-path in others — building the string once removes the question.
 */

import type { Metadata } from "next";

import type { BeadColor } from "@/lib/catalog";

/**
 * Where the site is published. Canonical URLs have to point there even when a
 * build runs locally with no NEXT_PUBLIC_BASE_PATH, so this is a setting of its
 * own rather than something derived from the base path.
 */
export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://djtobby.github.io/toho-beads-catalog"
).replace(/\/+$/, "");

export const SITE_NAME = "TOHO BEADS カタログ";

/** The word people actually search for; "TOHO BEADS" alone rarely gets typed. */
export const BRAND = "トーホービーズ";

export const MANUFACTURER = "トーホー株式会社";

/** Absolute URL for a route. `path` is a route, not a file under public/. */
export function siteUrl(path: string): string {
  return `${SITE_URL}${path}`;
}

export function colorPath(key: string): string {
  return `/colors/${encodeURIComponent(key)}/`;
}

export function catalogPagePath(n: number): string {
  return `/pages/${n}/`;
}

/**
 * One shared share image for every route.
 *
 * A per-colour card would be better, but next/og renders at request time and
 * this build has no server; pre-rendering 1,036 PNGs would put a few hundred
 * megabytes of derived artwork in the repository. public/og.png is generated by
 * pipeline/og_image.py alongside the other build artefacts.
 */
export const OG_IMAGE = {
  url: `${SITE_URL}/og.png`,
  width: 1200,
  height: 630,
  alt: `${BRAND}のグラスビーズカタログ`,
  type: "image/png",
} as const;

/** Metadata every route shares: canonical, OpenGraph, Twitter card. */
export function pageMetadata(o: {
  path: string;
  title: string;
  description: string;
}): Metadata {
  const url = siteUrl(o.path);
  return {
    title: o.title,
    description: o.description,
    alternates: { canonical: url },
    openGraph: {
      type: "website",
      locale: "ja_JP",
      siteName: SITE_NAME,
      url,
      title: o.title,
      description: o.description,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: o.title,
      description: o.description,
      images: [OG_IMAGE.url],
    },
  };
}

/** Unique finish variation names, in catalogue order. */
export function finishNames(color: BeadColor): string[] {
  return [...new Set(color.finishes.map((f) => f.variation))];
}

/** The size span the official photographs cover, as "特小ビーズ1.5mm〜丸大ビーズ3mm". */
function sizeSpan(color: BeadColor): string | null {
  const shapes = (color.official?.shapes ?? []).filter((s) => s.mm > 0);
  if (shapes.length < 2) return null;
  const sorted = [...shapes].sort((a, b) => a.mm - b.mm);
  const lo = sorted[0];
  const hi = sorted[sorted.length - 1];
  return `${lo.category}${lo.size}mm〜${hi.category}${hi.size}mm`;
}

export function catalogPagesOf(color: BeadColor): number[] {
  return [...new Set(color.appearances.map((a) => a.catalogPage))].sort((a, b) => a - b);
}

/**
 * Title for a colour page.
 *
 * The colour number leads because that is what gets typed ("トーホービーズ
 * 2113"), and the finish and hue family follow so that 1,036 titles do not read
 * as one title repeated — Google drops pages whose titles it treats as boilerplate.
 */
export function colorTitle(color: BeadColor): string {
  const traits = [...finishNames(color), `${color.color.family}系`].join("・");
  const series = color.reglass ? ` ${color.reglass.name}` : "";
  return `${BRAND}${series} カラーNo.${color.key}｜${traits}`;
}

/**
 * Description for a colour page, assembled from that colour's own record.
 *
 * Sentences are added while they fit, most distinguishing first, so a colour
 * with a thin record still gets a sentence that is true of it alone rather than
 * a padded template.
 */
export function colorDescription(color: BeadColor, productCodes: string[]): string {
  const words = color.official?.colorWords ?? [];
  const finish = finishNames(color).join("・");
  const types = color.beadTypes;
  const pages = catalogPagesOf(color);
  const span = sizeSpan(color);

  const sentences = [
    `${BRAND}のカラーNo.${color.key}（${color.color.family}系 ${color.color.hex}${
      words.length ? ` / ${words.join("・")}` : ""
    }）。`,
    finish ? `仕上げ加工は${finish}。` : "",
    color.reglass ? `ガラス瓶を再生した${color.reglass.name}の色です。` : "",
    types.length
      ? `${types.slice(0, 4).join("・")}${types.length > 4 ? `ほか計${types.length}種` : ""}で展開。`
      : "",
    productCodes.length
      ? `品番${productCodes.slice(0, 3).join("・")}${productCodes.length > 3 ? "ほか" : ""}の価格つき。`
      : "",
    span ? `${span}のサイズ比較。` : "",
    pages.length ? `ビーズカタログ2021 P.${pages.join("・")}掲載。` : "",
  ].filter(Boolean);

  return fitSentences(sentences, 155);
}

/** Keeps whole sentences up to `max` characters, always keeping the first. */
function fitSentences(sentences: string[], max: number): string {
  let out = "";
  for (const s of sentences) {
    if (out && out.length + s.length > max) continue;
    out += s;
  }
  return out;
}

type JsonLd = Record<string, unknown>;

/** The site itself, declared once on the home page. */
export function websiteJsonLd(colorCount: number): JsonLd {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": `${SITE_URL}/#website`,
    name: SITE_NAME,
    alternateName: `${BRAND} カラーカタログ`,
    url: siteUrl("/"),
    inLanguage: "ja",
    description: `${BRAND}のグラスビーズ${colorCount}色を、カラーNo.・品番・仕上げ加工・ビーズ種別・色から検索できるカタログ。`,
    about: { "@type": "Brand", name: "TOHO BEADS", alternateName: BRAND },
  };
}

export function breadcrumbJsonLd(trail: { name: string; path: string }[]): JsonLd {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: trail.map((t, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: t.name,
      item: siteUrl(t.path),
    })),
  };
}

/**
 * A colour as a product.
 *
 * No `offers`: the catalogue publishes 2021 list prices but the site sells
 * nothing, and an Offer that cannot be acted on is exactly what Google's
 * product guidelines rule out. The prices stay in the page body, where they are
 * described as what they are.
 */
export function colorProductJsonLd(
  color: BeadColor,
  o: { image: string | null; description: string; productCodes: string[] },
): JsonLd {
  const finish = finishNames(color);
  const properties: JsonLd[] = [
    { "@type": "PropertyValue", name: "カラーNo.", value: color.key },
    { "@type": "PropertyValue", name: "色系統", value: color.color.family },
    { "@type": "PropertyValue", name: "カラーコード", value: color.color.hex },
  ];
  if (finish.length) {
    properties.push({ "@type": "PropertyValue", name: "仕上げ加工", value: finish.join("・") });
  }
  if (color.beadTypes.length) {
    properties.push({
      "@type": "PropertyValue",
      name: "ビーズ種別",
      value: color.beadTypes.join("・"),
    });
  }
  if (o.productCodes.length) {
    properties.push({ "@type": "PropertyValue", name: "品番", value: o.productCodes.join("・") });
  }
  for (const shape of color.official?.shapes ?? []) {
    properties.push({
      "@type": "PropertyValue",
      name: shape.category,
      value: `外径約${shape.size}mm`,
    });
  }

  return {
    "@context": "https://schema.org",
    "@type": "Product",
    "@id": `${siteUrl(colorPath(color.key))}#product`,
    name: `${BRAND} カラーNo.${color.key}${finish.length ? `（${finish[0]}）` : ""}`,
    url: siteUrl(colorPath(color.key)),
    // A handful of colours have no crop clean enough to publish, and a
    // placeholder would be a claim about the bead that is not true.
    ...(o.image ? { image: o.image } : {}),
    description: o.description,
    color: color.color.family,
    material: "ガラス",
    brand: { "@type": "Brand", name: "TOHO BEADS", alternateName: BRAND },
    manufacturer: { "@type": "Organization", name: MANUFACTURER },
    category: "ビーズ・手芸材料 > シードビーズ",
    ...(o.productCodes.length === 1 ? { sku: o.productCodes[0] } : {}),
    additionalProperty: properties,
  };
}

/**
 * A catalogue scan. CreativeWork rather than ImageObject: the page is about the
 * printed spread, and the image is one of its representations.
 */
export function catalogPageJsonLd(o: {
  page: number;
  image: string;
  description: string;
  colorKeys: string[];
  source: string;
}): JsonLd {
  return {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    "@id": `${siteUrl(catalogPagePath(o.page))}#page`,
    name: `${o.source} P.${o.page}`,
    url: siteUrl(catalogPagePath(o.page)),
    description: o.description,
    inLanguage: "ja",
    primaryImageOfPage: { "@type": "ImageObject", contentUrl: o.image },
    isPartOf: { "@id": `${SITE_URL}/#website` },
    mainEntity: {
      "@type": "ItemList",
      numberOfItems: o.colorKeys.length,
      itemListElement: o.colorKeys.map((key, i) => ({
        "@type": "ListItem",
        position: i + 1,
        name: `カラーNo.${key}`,
        url: siteUrl(colorPath(key)),
      })),
    },
  };
}
