"""Bead shapes and sizes, transcribed from "ビーズの形状 目次" (catalogue pages 4-5).

Transcribed rather than OCR'd: the table's outer size column is small print and
the values are the ones the app quotes to shoppers, so they are worth being
exact about. `key` matches the names used in page_map.CHART_PAGES.
"""

# group, key, display name, size, notes
BEAD_TYPES: list[dict] = [
    # 丸ビーズ
    dict(group="丸ビーズ", key="特小", name="特小ビーズ", size="外径約1.5mm",
         note="外径が最も小さいビーズなので、より繊細な作品作りが楽しめます。"),
    dict(group="丸ビーズ", key="丸小", name="丸小ビーズ", size="外径約2.0〜2.2mm",
         note="最もポピュラーに使用されており、カラーバリエーションも豊富です。"),
    dict(group="丸ビーズ", key="丸中", name="丸中ビーズ", size="外径約2.6mm",
         note="全体的に丸みを帯びたビーズで、穴はやや大きめです。"),
    dict(group="丸ビーズ", key="丸大", name="丸大ビーズ", size="外径約3mm",
         note="最もポピュラーに使用されており、カラーバリエーションも豊富です。"),
    dict(group="丸ビーズ", key="特大4mm", name="特大ビーズ4mm", size="外径約4mm",
         note="穴が大きいので、ゴム紐やレザー紐を通してアームバンドやブレスレットに適しています。"),
    dict(group="丸ビーズ", key="特大5.5mm", name="特大ビーズ5.5mm", size="外径約5.5mm",
         note="穴が大きいので、ゴム紐やレザー紐を通してアームバンドやブレスレットに適しています。"),
    dict(group="丸ビーズ", key="Takumi LH丸小", name="Takumi LH丸小（穴大）", size="外径約2.0〜2.2mm",
         note="同サイズのビーズと比べて穴径が1割程度大きく、針やワイヤーを更に通しやすく、軽量化されています。"),
    dict(group="丸ビーズ", key="Takumi LH丸中", name="Takumi LH丸中（穴大）", size="外径約2.6mm",
         note="同サイズのビーズと比べて穴径が1割程度大きく、針やワイヤーを更に通しやすく、軽量化されています。"),
    dict(group="丸ビーズ", key="内角小", name="内角小", size="外径約2.0〜2.2mm",
         note="穴の形が四角形になっており、光の反射により華やかで奥行きのある輝きが出ます。"),
    dict(group="丸ビーズ", key="内角大", name="内角大", size="外径約3mm",
         note="穴の形が四角形になっており、光の反射により華やかで奥行きのある輝きが出ます。"),
    dict(group="丸ビーズ", key="DEMI丸小", name="DEMIビーズ丸小（厚薄）", size="外径約2.0〜2.2mm",
         note="通常の丸ビーズと直径・穴サイズは同じながら、厚みを薄くカットしてあります。"),
    dict(group="丸ビーズ", key="DEMI丸大", name="DEMIビーズ丸大（厚薄）", size="外径約3mm",
         note="通常の丸ビーズと直径・穴サイズは同じながら、厚みを薄くカットしてあります。"),
    dict(group="丸ビーズ", key="DEMI特大", name="DEMIビーズ特大（厚薄）", size="外径約4mm",
         note="通常の丸ビーズと直径・穴サイズは同じながら、厚みを薄くカットしてあります。"),
    dict(group="丸ビーズ", key="mimi特小", name="mimi（無穴）特小", size="外径約1.5mm",
         note="穴がないビーズで、デコレーションの素材などに適しています。"),
    dict(group="丸ビーズ", key="ヴィーダ", name="ヴィーダ（無穴）", size="外径約2.2〜4mm",
         note="穴がないビーズで、デコレーションの素材などに適しています。"),
    # カット系
    dict(group="スリーカットビーズ", key="スリーカット特小", name="スリーカット 特小ビーズ", size="外径約1.6mm",
         note="表面がランダムにカットされており、光の角度により輝きの変化が楽しめます。"),
    dict(group="スリーカットビーズ", key="スリーカット丸小", name="スリーカット 丸小ビーズ", size="外径約2.0〜2.2mm",
         note="表面がランダムにカットされており、光の角度により輝きの変化が楽しめます。"),
    dict(group="スリーカットビーズ", key="スリーカット丸大", name="スリーカット 丸大ビーズ", size="外径約3mm",
         note="表面がランダムにカットされており、光の角度により輝きの変化が楽しめます。"),
    dict(group="ダブルスリーカットビーズ", key="ダブルスリーカット丸小", name="ダブルスリーカット 丸小ビーズ",
         size="外径約2.0〜2.2mm", note="スリーカットビーズに比べカット面が多く、さらに輝きの変化が楽しめます。"),
    dict(group="ダブルスリーカットビーズ", key="ダブルスリーカット丸大", name="ダブルスリーカット 丸大ビーズ",
         size="外径約3mm", note="スリーカットビーズに比べカット面が多く、さらに輝きの変化が楽しめます。"),
    dict(group="シャーロットビーズ", key="シャーロット特小", name="シャーロット 特小ビーズ", size="外径約1.7mm",
         note="表面の1面をカットすることで、ワンポイントでの輝きの変化が楽しめます。"),
    dict(group="シャーロットビーズ", key="シャーロット丸小", name="シャーロット 丸小ビーズ", size="外径約2.0〜2.2mm",
         note="表面の1面をカットすることで、ワンポイントでの輝きの変化が楽しめます。"),
    # シリンダー系
    dict(group="アンティークビーズ", key="アンティーク丸小", name="アンティーク 丸小ビーズ", size="外径約1.65mm",
         note="ビーズ織りやビーズ刺繍に適した、シリンダー形状で穴が大きく軽量化されたビーズです。"),
    dict(group="アンティークビーズ", key="アンティーク角小", name="アンティーク 角小ビーズ", size="外径約1.65mm",
         note="ビーズ織りやビーズ刺繍に適した、シリンダー形状で穴が大きく軽量化されたビーズです。"),
    dict(group="トレジャービーズ", key="トレジャー丸小", name="トレジャー 丸小ビーズ",
         size="外径約1.65mm・長さ1.3mm", note="シリンダー形状のビーズです。"),
    dict(group="Aikoビーズ", key="Aiko丸小", name="Aiko 丸小ビーズ", size="外径約1.65mm・長さ1.3mm",
         note="粒揃いはTOHOで最高。仕上げ方法が正確で、ビーズ織りやビーズステッチに最適。柔らかな手触りに仕上がります。"),
    # マガ玉
    dict(group="マガ玉ビーズ", key="マガ玉3mm", name="マガ玉ビーズ3mm", size="外径約3mm",
         note="水滴のような丸味を帯びた形で、ガラス特有の艶を持っています。"),
    dict(group="マガ玉ビーズ", key="マガ玉4mm", name="マガ玉ビーズ4mm", size="外径約4mm",
         note="水滴のような丸味を帯びた形で、ガラス特有の艶を持っています。"),
    dict(group="マガ玉ビーズ", key="マガ玉5mm", name="マガ玉ビーズ5mm", size="外径約5mm",
         note="水滴のような丸味を帯びた形で、ガラス特有の艶を持っています。"),
    dict(group="マガ玉ビーズ", key="マガ玉7mm", name="マガ玉ビーズ7mm", size="外径約7mm",
         note="水滴のような丸味を帯びた形で、アクセサリーのポイントパーツに最適です。"),
    # 六角・四角・三角
    dict(group="六角ビーズ", key="六角特小", name="六角特小ビーズ", size="外径約1.5mm",
         note="表面が六角形になっており、光の角度によって柔らかな動きのある輝きが出ます。"),
    dict(group="六角ビーズ", key="六角小", name="六角小ビーズ", size="外径約2.0〜2.2mm",
         note="表面が六角形になっており、光の角度によって柔らかな動きのある輝きが出ます。"),
    dict(group="六角ビーズ", key="六角大", name="六角大ビーズ", size="外径約3mm",
         note="表面が六角形になっており、光の角度によって柔らかな動きのある輝きが出ます。"),
    dict(group="四角ビーズ", key="四角3mm", name="四角ビーズ3mm", size="外径約3mm",
         note="サイコロのような四角形で、面同士を接着させるなど形を生かした使い方が楽しめます。"),
    dict(group="四角ビーズ", key="四角4mm", name="四角ビーズ4mm", size="外径約4mm",
         note="穴が大きめなので、直接紐を通してアームバンドやレザーアクセサリーに適しています。"),
    dict(group="三角ビーズ", key="三角小", name="三角小", size="外径約2mm",
         note="表面が三角形になっており、光の角度によって大胆な動きのある輝きが出ます。"),
    dict(group="三角ビーズ", key="三角中", name="三角中", size="外径約2.2mm",
         note="表面が三角形になっており、光の角度によって大胆な動きのある輝きが出ます。"),
    dict(group="三角ビーズ", key="三角大", name="三角大", size="外径約2.4mm",
         note="表面が三角形になっており、光の角度によって大胆な動きのある輝きが出ます。"),
    dict(group="三角ビーズ", key="三角5mm", name="三角5mm", size="外径約5mm", note=""),
    dict(group="三角ビーズ", key="三角7mm", name="三角7mm", size="外径約7mm", note=""),
    # 竹・ツイスト
    dict(group="竹ビーズ", key="五厘竹", name="五厘竹", size="長さ約2mm",
         note="竹のように細長い形状で、長さによって五厘竹〜五分竹と名称が変わります。"),
    dict(group="竹ビーズ", key="一分竹", name="一分竹", size="長さ約3mm", note=""),
    dict(group="竹ビーズ", key="二分竹", name="二分竹", size="長さ約6mm", note=""),
    dict(group="竹ビーズ", key="三分竹", name="三分竹", size="長さ約9mm", note=""),
    dict(group="竹ビーズ", key="四分竹", name="四分竹", size="長さ約12mm", note=""),
    dict(group="竹ビーズ", key="五分竹", name="五分竹", size="長さ約15mm", note=""),
    dict(group="竹ビーズ", key="竹ビーズ", name="竹ビーズ", size="長さ約2〜15mm",
         note="竹のように細長い形状のビーズです。"),
    dict(group="ツイストビーズ", key="ツイストビーズ", name="ツイストビーズ", size="長さ約9〜15mm",
         note="表面をツイスト（ねじれ）させたビーズなので、しなやかな光沢が出ます。"),
    # その他
    dict(group="ミックスビーズ", key="ミックスビーズ", name="ミックスビーズ",
         size="丸小・丸大・一分竹・二分竹・特大・四角・マガ玉", note="複数の形・色を混ぜ合わせたビーズです。"),
    dict(group="パーツ", key="パーツ", name="UNISEX PARTS", size="—",
         note="糸通しビーズを使ったパーツ製品です。"),
]

SALES_STYLES: list[dict] = [
    dict(key="バラパック", name="TOHOバラパックビーズ",
         note="ブリスターパック式の容器入り。1箱5パック入り。", pack="縦90mm×横58mm"),
    dict(key="クィーン", name="クィーンビーズ",
         note="プラスチック製の八角ケース入り。フタはキャップ式。1箱6本入り。", pack="高さ67mm×直径14mm"),
    dict(key="Aiko・クィーン", name="Aikoビーズ／トレジャービーズ",
         note="Aikoはプラスチック製の袋入りで1箱5パック。トレジャーはクィーンビーズ容器入り。", pack="縦90mm×横41mm"),
    dict(key="糸通し", name="糸通しビーズ",
         note="1m分または0.5m分のビーズが糸に通してあります。束入り・箱入りもあります。", pack="縦90mm×横62mm"),
]
